services:
  web:
    image: todo-web:1.25
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  php:
    image: todo-php:8.3
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
